name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    services:
      emulator:
        image: gcr.io/cloud-spanner-emulator/emulator:latest
        ports:
          - 9010:9010
          - 9020:9020

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Setup GCloud
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Unit Tests
      working-directory: ./Google.Cloud.EntityFrameworkCore.Spanner.Tests
      run: dotnet test --no-build --verbosity normal
    - name: Integration Tests on Emulator
      working-directory: ./Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests
      # The emulator requires the integration tests to be run serially, so we temporarily
      # overwrite the default test configuration.
      run: |
        echo "{ \"parallelizeTestCollections\": false }" > xunit.runner.json
        dotnet test --verbosity normal
      env:
        JOB_TYPE: test
        SPANNER_EMULATOR_HOST: localhost:9010
        TEST_PROJECT: emulator-test-project
        TEST_SPANNER_INSTANCE: test-instance
    - name: Integration Tests on Production
      working-directory: ./Google.Cloud.EntityFrameworkCore.Spanner.IntegrationTests
      run: |
        echo "{ \"parallelizeTestCollections\": true, \"maxParallelThreads\": 4 }" > xunit.runner.json
        dotnet test --verbosity normal
      env:
        JOB_TYPE: test
        TEST_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
